title: "Devansh Khare"
email: kharedevansh16@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Infosec enthusiast | Flutter Developer
            OSCP | CEH
baseurl: "/" 
url: "https://darkmoron.github.io/" 
twitter_username: lifelesshump
github_username:  DarkMoron

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
